Update dev-deploy-aks.yml

diff --git a/.github/workflows/dev-deploy-aks.yml b/.github/workflows/dev-deploy-aks.yml
--- a/.github/workflows/dev-deploy-aks.yml
+++ b/.github/workflows/dev-deploy-aks.yml
@@ -79,7 +79,12 @@ jobs:
       - name: Deploy to AKS
         run: >
           kubectl apply -f .github/k8s/deployment-service-aks.yml
-
+      - name: Debug Deployment Sataus
+        run: |
+          echo "Describing deployment and listing resources.
+          kubectl describe deployment event-driven-repo -n ${{ env.NAMESPACE }} || echo "Deployment not found"
+          kubectl get all -n ${{ env.NAMESPACE }}
+          
           kubectl rollout status deployment event-driven-repo -n ${{ env.NAMESPACE }} --timeout=60s
       - name: Wait for External IP
         id: get-ip
